export const newsMessages = [
    "This is the first news message in the entire game!",
    "oops the game bugged so your save got wiped",
    "One day, you will stop your grinding.",
    "ₜₕᵢₛ ₜₑₓₜ ᵢₛ ₛₘₒₗ",
    "Use blind notation for better experience",
    "If you think the game is not fun, it gets even worse later to the point that it's fun!",
    "Once upon a time, nothing happened...",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAntimatter Dimensions is a really good game",
    "I hate this - me",
    "[THIS NEWS MESSAGE HAS BEEN DELETED]",
    "Next update coming tomorrow",
    "Look at what you've done, it all started with the 'get a point' button...",
    `If this number: ${Math.floor(Math.random()*100)} is larger than 90, consider yourself lucky!`,
    "haha points go brrrrrrrrrrrrrrrrr",
    "how much references does this game have",
    "Your ordinal is H_ω²+ω5+6 (10), press i to markup for 156 ordinal points... Wait, wrong game",
    "onion",
    `Here's a way to get free points, the devs don't want you to know. First, go into the options tab, then click the big red friendly 
RESET THE GAME button, then just click confirm and do whatever it tells you, now, you will have free points! Disclamer: might wipe your save`,
    "no cheating",
    "we ran out of news messages k bye",
    "\"Most quotes on the internet are falsely attributed\" - Hevipelle",
    "Click here to do nothing!",
    "This game is absolutely not a clone of antimatter dimensions",
    "Wait... If you say you are smart and you say that it's a joke, doesn't it make YOU a joke?",
    "first",
    `i know you are expecting a news message, but i think that it is better for you to play the game instead, 
so this news message is just going forever and forever and forever and forever and forever and forever and 
forever and forever and forever and forever and forever and forever and forever and forever and i was actually lying`,
    "<button onclick='window.alert(\"Yay!\")'>This is a button!</button>",
    "This message is (softcapped)",
    "<a href='https://www.youtube.com/watch?v=dQw4w9WgXcQ'>https://www.youtube.com/watch?v=dQw4w9WgXcQ</a>",
    "guys im trying to think of news message but i just cant pls help me",
    "What is the point if you have no points?",
    "The game is bad. Stop playing while you still can.",
    "Me trying to not start inflation be like:",
    "Did you know that if that you know that if you know that if only you know that only if you do know that only if you know?",
    "Do you know whats better than an unfunny and unoriginal joke?",
    '"This game is stoopid" - My friend',
    "Some people say this game has good balancing, and some say not. I, personally think this game's balancing is the worst of all games",
    "banana",
    "banananananananananananananananananananananananananananananananananananananananana",
    "The update is NOT coming tomorrow",
    "Guys I forgot this one, can you just ignore it?",
    "The previous news message is VERY VERY important, I hope you saw it",
    "Onion is gud, banana is also gud",
    "sory fur bed engrsh",
    "Did you know that you are progressing slower than 87% of people according to statistics?",
    "sudo rm -rf /*",
    "Delete System32 on your computer to get better performance!",
    "hello",
    "<button onclick='alert(\"Error: Permission denied\")'>Click here to permanently break your device!</button>"
];

